apiVersion: v1
kind: Service
metadata:
  name: users-app-service
  labels:
    app: users-service
spec:
  ports:
    - port: 80
  selector:
    app: users-app
---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: users-app
  name: users
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: users-app
    spec:
      containers:
        - name: users
          image: users
          ports:
            - containerPort: 80
              name: users        